#            _______    _ _      ______   __  __  ____ _______ _____  
#     /\    |___  / |  | | |    |  ____| |  \/  |/ __ \__   __|  __ \ 
#    /  \      / /| |  | | |    | |__    | \  / | |  | | | |  | |  | |
#   / /\ \    / / | |  | | |    |  __|   | |\/| | |  | | | |  | |  | |
#  / ____ \  / /__| |__| | |____| |____  | |  | | |__| | | |  | |__| |
# /_/    \_\/_____|\____/|______|______| |_|  |_|\____/  |_|  |_____/ 
# VERSÃO: 1.0                            CRÉDITOS: AZULECODES


# VARIÁVEIS:
# {nl} - Cria uma nova linha;

MOTD:
  Motd01: "&b&lAzuleMOTD &7- &8(1.8.8){nl}&fTestando meu novo MOTD!" #MOTD normal do servidor!
  Motd02: "&4&lAzuleMOTD &7- &8(1.8.8){nl}&fServidor em manuntenção!" #MOTD de manuntenção do servidor!
  
FAKEVERSION: #Texto que aparece em cima dos jogadores online.
  Enabled: true #Você quer esta função ativa?
  WhitelistOnly: true #Você quer que esta função apenas funcione com a Whitelist ligada?
  Fake01: "&b&lAzuleMOTD!" #Texto que aparece normalmente.
  Fake02: "&4&lAzuleMOTD!" #Texto que aparece com a whitelist ligada.
  
HOVERENABLED: false
HOVERTEXT: #Texto que aparece quando o cursor está em cima dos jogadores online.
- '&b&lAzuleMOTD' #Pode criar quantas linhas quiser, YAY!
- '&fTestando o meu novo MOTD!'
- '&bBy: AzuleCodes'